# Generated by Django 5.1.6 on 2025-02-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tmmaddress',
            new_name='tmaddress',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tmmwork',
            new_name='tmwork',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tmmname',
        ),
    ]
