# Generated by Django 5.1.6 on 2025-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tmname',
            field=models.CharField(max_length=100),
        ),
    ]
